### ISSUE TITLE
【研修】NuxtJS+Firebase Storageで画像管理アプリを作成する

### ISSUE THREAD

**Issue by ryo-hagiwara-fate** [Nutz0215/dolphin#3]
### 概要

次の記事に従って、NuxtJSで画像管理アプリを作成する。

https://zenn.dev/aono/articles/18db43acde192a

### TODO

- [ ] ブランチを切って移動
- [ ] Firebaseの設定
- [ ] .envファイルについての理解
- [ ] Firebase Storage の設定
- [ ] 記事の「アップロード処理作成」のコードをコピーして動作確認し、コードを理解する
- [ ] 「画像の表示（ダウンロード）処理作成」も同様にコピーして理解

### 注意
わからなかったらこのissueにコメントすること。その場合メンションをつけること。

**Comment by ryo-hagiwara-fate** [comment]
### envファイルについて
この記事がとてもわかりやすい

https://maku77.github.io/nodejs/env/dotenv.html

**Comment by ryo-hagiwara-fate** [comment]
このサンプルはvuetifyではなくてbeufyじゃないと動かない。最初からプロジェクトを作り直す。

そしてindex.vueにこれを貼り付ければ画面自体はできる

```
<template>
  
  <b-field>
  <h2 class="title is-3 has-text-grey">新規投稿</h2>
  <b-field label="タイトル">
    <b-input v-model="title" required></b-input>
  </b-field>
  <b-field label="メモ">
    <b-input rows="2" maxlength="100" type="textarea" v-model="memo"></b-input>
  </b-field>

  <b-upload v-model="file" drag-drop required>
    <section class="section">
      <div class="content has-text-centered">
        <p>
          <b-icon icon="upload" size="is-large"> </b-icon>
        </p>
        <p>画像ファイルをドロップしてください。</p>
      </div>
    </section>
  </b-upload>
</b-field>

</template>

<script>
export default {
  data() {
    return {
      title: "",
      memo: "",
      file: null,
      type: "",
      dataUrl: "",
    };
  },
  methods: {
    create() {
      this.$store.dispatch("items/create", {
        title: this.title,
        memo: this.memo,
        file: { name: this.fileName, type: this.type, dataUrl: this.dataUrl },
      });
    },
  },
  watch: {
    file(val) {
      this.fileName = val.name;
      if (val.type == "image/jpeg") this.type = "jpeg";
      else if (val.type == "image/png") this.type = "png";
      else if (val.type == "image/gif") this.type = "gif";
      const reader = new FileReader();
      reader.readAsDataURL(this.file);
      reader.onload = (e) => {
        this.dataUrl = e.target.result;
      };
    },
  },
};
</script>

```
